version: '3'

services:
  database:
    image: mysql
    container_name: database3
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    volumes:
      - dockerAngularSpringDatabaseData:/var/lib/mysql
      
  spring-boot:
    image: ahmed991/backend:41
    container_name: spring-boot3
    ports:
      - 8080:8080
    depends_on:
      - database
    environment:

       SPRING_APPLICATION_JSON: '{

        "spring.datasource.url" : "jdbc:mysql://database3:$MYSQLDB_DOCKER_PORT/$MYSQLDB_DATABASE?allowPublicKeyRetrieval=true&useSSL=FALSE",

        "spring.datasource.username" :"$MYSQLDB_USER" ,

        "spring.datasource.password" :"$MYSQLDB_ROOT_PASSWORD" ,

        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",

        "spring.jpa.hibernate.ddl-auto" : "update"}'
   
      
  angular:
    image: ahmed991/front:19
    container_name: angular3
    ports: 
      - 4200:80
    depends_on:
      - spring-boot


volumes:
  dockerAngularSpringDatabaseData:
  

